// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUySn1IGiLg30IaLtig_43FPLTjl_Zb8E',
    appId: '1:822658824377:android:75240d1575d14b099fc368',
    messagingSenderId: '822658824377',
    projectId: 'delivery-taxi-17959',
    storageBucket: 'delivery-taxi-17959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EOonXemaPS5gYofM3QmJ5JrL_U6vPis',
    appId: '1:822658824377:ios:5eb4b6f50692fa489fc368',
    messagingSenderId: '822658824377',
    projectId: 'delivery-taxi-17959',
    storageBucket: 'delivery-taxi-17959.appspot.com',
    iosBundleId: 'com.delivery.taxi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnOce21T6t8uWWDaRVO9Lru5BtRwZ811w',
    appId: '1:822658824377:web:60ddf0a4f23650929fc368',
    messagingSenderId: '822658824377',
    projectId: 'delivery-taxi-17959',
    authDomain: 'delivery-taxi-17959.firebaseapp.com',
    storageBucket: 'delivery-taxi-17959.appspot.com',
    measurementId: 'G-0GPP4J3KTZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EOonXemaPS5gYofM3QmJ5JrL_U6vPis',
    appId: '1:822658824377:ios:13154ee1185440f49fc368',
    messagingSenderId: '822658824377',
    projectId: 'delivery-taxi-17959',
    storageBucket: 'delivery-taxi-17959.appspot.com',
    iosBundleId: 'com.example.deliveryTaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnOce21T6t8uWWDaRVO9Lru5BtRwZ811w',
    appId: '1:822658824377:web:5b5053b8bf51de5f9fc368',
    messagingSenderId: '822658824377',
    projectId: 'delivery-taxi-17959',
    authDomain: 'delivery-taxi-17959.firebaseapp.com',
    storageBucket: 'delivery-taxi-17959.appspot.com',
    measurementId: 'G-STE048XS72',
  );

}